name: landslide_usecase
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pymt>=1.3.1
  - cdsapi
  - pymt_topography
  - pymt_era5
  - imageio-ffmpeg
  - numpy=1.23.5
  - xesmf
  - xarray
  - rioxarray
  - cftime
  - imageio>=2.19.1
  - matplotlib
  - jupyter
  - tqdm
  