bmi-era5:
  name: reanalysis-era5-single-levels
  request:
    variable:
      - total_precipitation
      - volumetric_soil_water_layer_1
      - volumetric_soil_water_layer_2
      - volumetric_soil_water_layer_3
      - volumetric_soil_water_layer_4
    product_type: reanalysis
    year: 2017
    month: 09
    day:
      - '20'
      - '21' 
      - '22'
      - '23'
     
    time:
      - '00:00'
      - '01:00'
      - '02:00'
      - '03:00'
      - '04:00'
      - '05:00'
      - '06:00'
      - '07:00'
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
      - '13:00'
      - '14:00'
      - '15:00'
      - '16:00'
      - '17:00'
      - '18:00'
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
      - '23:00'
    format: netcdf
    area:
      - 18.30
      - -66.75
      - 18.05
      - -66.25
    grid:
      - 0.25
      - 0.25
  path: './cache_puerto_rico/era5.nc'

